# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rag_pb2 as rag__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rag_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RagServiceStub(object):
    """The gRPC service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessDocument = channel.unary_unary(
                '/rag.RagService/ProcessDocument',
                request_serializer=rag__pb2.ProcessRequest.SerializeToString,
                response_deserializer=rag__pb2.ProcessResponse.FromString,
                _registered_method=True)
        self.AnswerQuery = channel.unary_unary(
                '/rag.RagService/AnswerQuery',
                request_serializer=rag__pb2.QueryRequest.SerializeToString,
                response_deserializer=rag__pb2.QueryResponse.FromString,
                _registered_method=True)


class RagServiceServicer(object):
    """The gRPC service definition.
    """

    def ProcessDocument(self, request, context):
        """Processes a document: reads, chunks, embeds, and stores it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnswerQuery(self, request, context):
        """Answers a query based on the document context.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RagServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessDocument,
                    request_deserializer=rag__pb2.ProcessRequest.FromString,
                    response_serializer=rag__pb2.ProcessResponse.SerializeToString,
            ),
            'AnswerQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.AnswerQuery,
                    request_deserializer=rag__pb2.QueryRequest.FromString,
                    response_serializer=rag__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rag.RagService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rag.RagService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RagService(object):
    """The gRPC service definition.
    """

    @staticmethod
    def ProcessDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/ProcessDocument',
            rag__pb2.ProcessRequest.SerializeToString,
            rag__pb2.ProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnswerQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/AnswerQuery',
            rag__pb2.QueryRequest.SerializeToString,
            rag__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
