# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trag.proto\x12\x03rag\"8\n\x0eProcessRequest\x12\x15\n\rdocument_path\x18\x01 \x01(\t\x12\x0f\n\x07\x63hat_id\x18\x02 \x01(\t\"3\n\x0fProcessResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"3\n\x0cQueryRequest\x12\x12\n\nquery_text\x18\x01 \x01(\t\x12\x0f\n\x07\x63hat_id\x18\x02 \x01(\t\"\x1f\n\rQueryResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2\x84\x01\n\nRagService\x12>\n\x0fProcessDocument\x12\x13.rag.ProcessRequest\x1a\x14.rag.ProcessResponse\"\x00\x12\x36\n\x0b\x41nswerQuery\x12\x11.rag.QueryRequest\x1a\x12.rag.QueryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSREQUEST']._serialized_start=18
  _globals['_PROCESSREQUEST']._serialized_end=74
  _globals['_PROCESSRESPONSE']._serialized_start=76
  _globals['_PROCESSRESPONSE']._serialized_end=127
  _globals['_QUERYREQUEST']._serialized_start=129
  _globals['_QUERYREQUEST']._serialized_end=180
  _globals['_QUERYRESPONSE']._serialized_start=182
  _globals['_QUERYRESPONSE']._serialized_end=213
  _globals['_RAGSERVICE']._serialized_start=216
  _globals['_RAGSERVICE']._serialized_end=348
# @@protoc_insertion_point(module_scope)
